//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,7.3481
        ///2,6.5437
        ///3,5.8237
        ///4,5.1894
        ///5,4.6213
        ///6,4.1154
        ///7,3.6649
        ///8,3.2636
        ///9,2.9064
        ///10,2.5882
        ///11,2.3048
        ///12,2.0525
        ///13,1.8278
        ///14,1.6277
        ///15,1.4495
        ///16,1.2908
        ///17,1.1495
        ///18,1.0237
        ///19,0.9116
        ///20,0.8118
        ///21,0.7229
        ///22,0.6438
        ///23,0.5733
        ///24,0.5106
        ///25,0.4547
        ///26,0.4049
        ///27,0.3606
        ///28,0.3211
        ///29,0.2859
        ///30,0.2546
        ///31,0.2268
        ///32,0.2019
        ///33,0.1798
        ///34,0.1601
        ///35,0.1426
        ///36,0.1270
        ///37,0.1131
        ///38,0.1007
        ///39,0.0897
        ///40,0.0799.
        /// </summary>
        public static string AWG {
            get {
                return ResourceManager.GetString("AWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25,0.5
        ///29,0.55
        ///31,0.575
        ///38,0.65
        ///42,0.7
        ///46,0.75
        ///51,0.8
        ///57,0.85
        ///62,0.9
        ///65,0.925
        ///68,0.95
        ///74,1
        ///100,1.04
        ///117,1.05
        ///127,1.075
        ///138,1.1
        ///150,1.125
        ///180,1.15
        ///226,1.17
        ///231,1.18
        ///250,1.2
        ///321,1.215
        ///365,1.225
        ///424,1.23
        ///474,1.24
        ///500,1.25
        ///573,1.255
        ///698,1.26
        ///784,1.265
        ///870,1.27
        ///1000,1.275
        ///1104,1.278
        ///1263,1.286
        ///1369,1.289
        ///1500,1.3
        ///1600,1.3
        ///1700,1.3.
        /// </summary>
        public static string Bg {
            get {
                return ResourceManager.GetString("Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,7.62
        ///2,7.213
        ///3,6.579
        ///4,6.045
        ///5,5.588
        ///6,5.156
        ///7,4.572
        ///8,4.119
        ///9,3.759
        ///10,3.404
        ///11,3.048
        ///12,2.769
        ///13,2.413
        ///14,2.108
        ///15,1.829
        ///16,1.651
        ///17,1.473
        ///18,1.245
        ///19,1.067
        ///20,0.888
        ///21,0.813
        ///22,0.711
        ///23,0.635
        ///24,0.559
        ///25,0.508
        ///26,0.457
        ///27,0.406
        ///28,0.356
        ///29,0.330
        ///30,0.305
        ///31,0.254
        ///32,0.229
        ///33,0.203
        ///34,0.178
        ///35,0.127
        ///36,0.102.
        /// </summary>
        public static string BWG {
            get {
                return ResourceManager.GetString("BWG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap download_32 {
            get {
                object obj = ResourceManager.GetObject("download_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flat_armature {
            get {
                object obj = ResourceManager.GetObject("flat armature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flat_armature_32 {
            get {
                object obj = ResourceManager.GetObject("flat armature_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flat_armature1 {
            get {
                object obj = ResourceManager.GetObject("flat armature1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horse_shoe_32 {
            get {
                object obj = ResourceManager.GetObject("horse shoe_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Inkedplunger_LI_32 {
            get {
                object obj = ResourceManager.GetObject("Inkedplunger_LI_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15,0.000934
        ///17.5,0.000943
        ///20,0.00095
        ///22.5,0.00096
        ///25,0.00097
        ///27.5,0.000977
        ///30,0.000985
        ///32.5,0.00996
        ///35,0.001
        ///37.5,0.00101
        ///40,0.00102
        ///42.5,0.0103
        ///45,0.00104
        ///47.5,0.00105
        ///50,0.001059
        ///52.5,0.00106
        ///55,0.00107
        ///57.5,0.00108
        ///60,0.00109
        ///62.5,0.0011
        ///65,0.00111
        ///67.5,0.00112
        ///70,0.001127
        ///72.5,0.00113
        ///75,0.00115
        ///77.5,0.00157
        ///80,0.00116
        ///82.5,0.00117
        ///85,0.00118
        ///87.5,0.00119
        ///90,0.0012
        ///92.5,0.001209
        ///95,0.00121
        ///97.5,0.00122
        ///100,0.00123
        ///102.5,0.00125
        ///105,0.001253
        ///107.5,0.00126
        ///110,0.00127
        ///112.5,0.0128
        ///115,0.00129
        ///117.5,0.0013 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Lambda {
            get {
                return ResourceManager.GetString("Lambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,7.620
        ///2,7.01
        ///3,6.401
        ///4,5.893
        ///5,5.385
        ///6,4.877
        ///7,4.470
        ///8,4.064
        ///9,3.658
        ///10,3.251
        ///11,2.946
        ///12,2.642
        ///13,2.337
        ///14,2.032
        ///15,1.829
        ///16,1.626
        ///17,1.422
        ///18,1.219
        ///19,1.016
        ///20,0.914
        ///21,0.813
        ///22,0.711
        ///23,0.610
        ///24,0.559
        ///25,0.5080
        ///26,0.4572
        ///27,0.4166
        ///28,0.3759
        ///29,0.3454
        ///30,0.3150
        ///31,0.2946
        ///32,0.2743
        ///33,0.2540
        ///34,0.2337
        ///35,0.2134
        ///36,0.1930
        ///37,0.1727
        ///38,0.1524
        ///39,0.1321
        ///40,0.1219.
        /// </summary>
        public static string SWG {
            get {
                return ResourceManager.GetString("SWG", resourceCulture);
            }
        }
    }
}
